### ISSUE TITLE
Application menu doesn't show in plank dock

### ISSUE THREAD

**Issue by marcelovbcfilho** [hardpixel/dash-to-plank#1]
As I saw at the preview images I suppose that the Show Applications button would appear, but with Gnome 40 and opensuseTUMBLEWEED isn't the case. I don't know if this could be a bug because of an old plank installation tho.
![Screenshot from 2021-04-15 08-43-57](https://user-images.githubusercontent.com/51462138/114864012-db1b0a80-9dc6-11eb-9abb-e16e24f6f60c.png)

**Comment by jonian** [comment]
Hi @marcelovbcfilho, the extension has some issues on initialization that I'm working on now. 

If you restart the shell with Alt+F2 it should work. It will replace the items from the old plank installation with your dash favorites and add the Show Applications button. 

It might mess your favorites ordering though, so use at your own risk.

I will release a new version when the initialization issue is fixed.

**Comment by marcelovbcfilho** [comment]
Oh true, I restarted the shell and it works, thanks, and it doesn't mess with my favorite order.
