### ISSUE TITLE
Show applications not working in gnome shell 41

### ISSUE THREAD

**Issue by Unixware** [hardpixel/dash-to-plank#12]
I may be rushing and use this , but I am reporting in any case: on Fedora 35 -I know its beta  : 

When I click on the "Applications" does not show anything, I am getting the "bounce" feedback anyway.
Probably not compatible with Gnome 41? 

thanks!

**Comment by jonian** [comment]
Hi @Unixware, can you try the commands below:

```sh
# Show applications
dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.ShowApplications

# Show overview
dbus-send --session --dest=org.gnome.Shell --type=method_call /org/gnome/Shell org.freedesktop.DBus.Properties.Set string:org.gnome.Shell string:OverviewActive variant:boolean:true
```

If they do not work, use D-Feet or the DBus inspector from Gnome Builder to see if the dbus actions have changed in the new version.

**Comment by Hellwarson** [comment]
Same problem on openSUSE tumbleweed with gnome 41.

Show overview command works but not Show applications command.

It is the same problem if you only have Plank installed so I don't think this is related to Dash to Plank.

**Comment by Unixware** [comment]
commands do not work , sorry.

I installed the d-feet : at the Session bus > org.gnome.shell > interfaces > org.gnome.shell > methods > ShowApplications () -> ()

**Comment by jonian** [comment]
@Unixware does it work when you execute it from D-Feet?

**Comment by Unixware** [comment]
mate execute what ? I am not gnome developer!  but if I double click on that (ShowApplications) and run the "execute"
says : 
```
('g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: '
 'ShowApplications is not allowed (9)')
```

I assume it needs something into the "method input" ...?

**Comment by Unixware** [comment]
btw is anything that I can run eg on that debug tool "looking glass" ? it may produce some meaningful to you.thx

**Comment by Hellwarson** [comment]
ShowApplications has no value in D-feet.

ShowApplications () -> ()

**Comment by Unixware** [comment]
sorry as I see the "show overview" works on my setup, like @Hellwarson wrote..

**Comment by Hellwarson** [comment]
Found the reason and solution for now: https://extensions.gnome.org/extension/4517/unsafe-mode/

**Comment by Unixware** [comment]
lovely ... it works!  many thanks!!

**Comment by jonian** [comment]
Extension should not rely on third party extensions to work
