### ISSUE TITLE
Plank Error When Remove Dash To Plank

### ISSUE THREAD

**Issue by aldiwira** [hardpixel/dash-to-plank#13]
When i remove dash to plank extension. and using plank again. i found this error on plank logger.

`Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.Extensions.DashToPlank” on object at path /org/gnome/Shell/Extensions/DashToPlank
`
is there any solution to fix this?

**Comment by jonian** [comment]
Hi @aldiwira, re-install dash-to-plank and remove the applications shortcut. Then remove the extension.
