### ISSUE TITLE
Dash to Plank causing delay of desktop display after login to GDM

### ISSUE THREAD

**Issue by edgan** [hardpixel/dash-to-plank#16]
I just upgraded to Fedora 36, and hence Gnome 42. I was logging in and out repeating to fix various issues that cropped up. In the process an existing issue I have had for a while became annoying enough I started chasing it down.

  The issue I have is that on login into my account via GDM with an Xorg session it takes something like 20 seconds to get the desktop with Gnome. I say with Gnome, because I do get a black background sooner, but nothing else. If I disable Dash to Plank it is instant.

Details:
Dash to Plank 13
Fedora 36(Also seen on Fedora 35)
xorg-x11-server-Xorg-1.20.14-5.fc36.x86_64
gdm-42.0-2.fc36.x86_64
gnome-shell-42.0-3.fc36.x86_64
plank-0.11.89-10.20210202.git013d051.fc36.x86_64

**Comment by Yv-vY** [comment]
Same issue on my side.
