### ISSUE TITLE
Dock position breaks when connecting external monitors

### ISSUE THREAD

**Issue by garhul** [hardpixel/dash-to-plank#18]
Adding an external monitor sometimes causes the dock to float in a position that corresponds to the coordinates of the previous resoulution of the main screen. 

So let's say my main screen is in 1080p, when connecting an external monitor with a resolution of 1440p the dock floats somewhere around the lower right quadrant of the screen, looks like the coordinates in use are those that were taken for the positioning in the original screen.

This was a problem with Plank as well, so not sure if this may be solvable from this extension. A workaround is to disable and reenable the extension after the monitor is connected.

**Comment by jonian** [comment]
Hi @garhul, thanks for the report. The extension does not control the positioning of plank (not possible). It would be better if you reported this issue upstream. Github repo is [here](https://github.com/ricotz/plank) but the issues are not enabled. Their issue tracker is on Launchpad [here](https://bugs.launchpad.net/plank).
