### ISSUE TITLE
Gnome 40 theming

### ISSUE THREAD

**Issue by Spinnekop** [hardpixel/dash-to-plank#2]
Hi. Any chance of providing a theme so the plank looks like the dock in overview in gnome 40? Also, does this work with Wayland?

**Comment by jonian** [comment]
Hi @Spinnekop, there are no plans to provide a plank theme that matches the dash theme.

You can search for a theme that you like on [Gnome Look](https://www.gnome-look.org/browse/cat/273/), or create your own theme as it is very easy.

**Comment by jonian** [comment]
@Spinnekop, it does not work on wayland because Plank does not support wayland.
