### ISSUE TITLE
Show Date Time

### ISSUE THREAD

**Issue by patricklibert** [hardpixel/dash-to-plank#20]
I now that you have a clock with plank but is it possible to show date time like the gnome extension dash to panel?
Right in the taskbar?

Would be nice

**Comment by jonian** [comment]
Hi @patricklibert, unfortunately it is not possible to do from the extension. It needs to be implemented as a plank docklet. Even if I create a docklet, it can't be shipped with the extension because gnome extensions website does not allow uploading binary files.

**Comment by patricklibert** [comment]
Thanks for the info
