### ISSUE TITLE
Cant Add or Remove Apps from plank

### ISSUE THREAD

**Issue by theproduct86** [hardpixel/dash-to-plank#5]
I can't add or remove any app shortcuts to my plank. I no options when I right click and item nor can i click and drag off like my normal plank. now when I uninstall extension i dont get back the normal plank functionality as before.

**Comment by jonian** [comment]
Hi @theproduct86, run `plank --preferences` and change to default or some other theme and then enable the extension. Does it fix the issue?

**Comment by theproduct86** [comment]
For some reason the icon lock was on but wouldn't turn off. Kept clicking the switch only for it switch right back to on. uninstall plank and the extension rebooted and installed again and fixed the issue icon lock was turned off and stayed off
