### ISSUE TITLE
Dash to Plank doesn't work on Fedora 34..!!

### ISSUE THREAD

**Issue by zerocoolroot** [hardpixel/dash-to-plank#6]
Hi,

Firstly, thank you by your extension..!!

Dash to Plank doesn't work on Fedora 34.

"Plank not avaliable on your system".

![Screenshot](https://user-images.githubusercontent.com/44586443/115941735-0c59a180-a47d-11eb-9522-31a744178794.png)

Thanks in advance..!!

**Comment by jonian** [comment]
Install plank then run the extension. That is what "Plank not avaliable on your system" means. 

Also the description in gnome extensions website says "To use this extension, you must have Plank installed on your system." and the readme in this repository says "Make sure you have installed Plank".

**Comment by jonian** [comment]
@zerocoolroot I have updated the readme to make it more obvious that plank must be installed with examples for Ubuntu, Fedora and Arch Linux.
