### ISSUE TITLE
Add setting to not put "Show Applications" item on the dock

### ISSUE THREAD

**Issue by p1zz4br0etch3n** [hardpixel/dash-to-plank#8]
I'd like to have an extension setting to not put the "Show Applications" item on the dock. I don't need it and when I remove it manually, it automatically re-appears from time to time. Would be nice if one could disable that behaviour.

**Comment by jtjh** [comment]
Iv had this bug as well, every time I remove it, it just pops straight back.

**Comment by jonian** [comment]
I added a setting to disable the apps launcher. There is no settings UI for now and you can toggle the setting using:

```sh
# If the extension is installed globally

gsettings set org.gnome.shell.extensions.dash-to-plank show-apps-icon false
```

```sh
# If you have the extension installed locally

gsettings --schemadir ~/.local/share/gnome-shell/extensions/dash-to-plank@hardpixel.eu/schemas set org.gnome.shell.extensions.dash-to-plank show-apps-icon false
```
